DROP TABLE IF EXISTS employee;

CREATE TABLE employee (
id LONG AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
secondName VARCHAR(255) NOT NULL,
surname VARCHAR(255) NOT NULL,
gender VARCHAR(255) NOT NULL,
pesel LONG NOT NULL,
nationality VARCHAR(255) NOT NULL,
dateOfBirth DATE NOT NULL,
telephone VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL
);